services:
  - type: web
    name: parlando-space-game
    runtime: docker
    plan: starter
    dockerfilePath: ./space-game/Dockerfile
    disk:
      name: parlando-data
      mountPath: /data
      sizeGB: 1
